### ISSUE TITLE
Need contributor guide

### ISSUE THREAD

**Issue by jnoller** [jrperritt/rack#13]
How does someone add a new service? How do we make this self-service for command additions, features? How much is upstream gophercloud?

**Comment by jrperritt** [comment]
> How does someone add a new service? How do we make this self-service for command additions, features?

Adding commands for any service is done exactly like it is for [`compute`](https://github.com/jrperritt/rackcli/tree/master/computecommands). I can write up something about it.

> How much is upstream gophercloud?

All the logic except for authentication methods, input (arguments and flags), and output (tables) should be handled by Gophercloud. For example, an error due to an incorrect flag name or an incorrect number of arguments will come from rackcli. However, as long as the flag names/types and argument number are correct, the error (for example, due to a missing required flag) will come from Gophercloud.

**Comment by kenperkins** [comment]
I don't see anything in 5076d41 that resolves this.

**Comment by kenperkins** [comment]
I'll take a stab at throwing this together today.
