### ISSUE TITLE
Provide a way to see all the API calls going over the wire

### ISSUE THREAD

**Issue by annegentle** [jrperritt/rack#40]
Feature request: As a CLI user I need to know the underlying API calls so that I can learn the reference information or debug why the command isn't working as expected.

**Comment by rtgoodwin** [comment]
Big +1. Our mobile app developers have given me first hand experience in how powerful being able to do this is, once I got them all setup with the Openstack tools and --debug! Drastically reduced the learning curve for common operations.

**Comment by kenperkins** [comment]
Can this be done without plumbing logging event support into gophercloud? If not, we should move this to post-mvp.

**Comment by jrperritt** [comment]
We can't really avoid having the debugging logic live in Gophercloud, since that'll be where the final HTTP request state is before it gets sent over the wire. However, I have an idea for doing this that would take less than an hour to implement (in Gophercloud). With it, we could send all the HTTP request data to the user.

**Comment by kenperkins** [comment]
As of today, we don't have anything in `rack` today.

**Comment by jrperritt** [comment]
This is blocked pending a PR to gophercloud: https://github.com/rackspace/gophercloud/pull/441
