### ISSUE TITLE
paginate long output

### ISSUE THREAD

**Issue by jnoller** [jrperritt/rack#48]
Assuming users could get LOTS of results back from a given call, do we add a --paginate or default to pagination and offer a --no-paginate?

**Comment by jrperritt** [comment]
Would this just be for `list` commands?

**Comment by jnoller** [comment]
I think that would be ok to start with

**Comment by jrperritt** [comment]
It's ok if there are others. I'm just trying to get an idea of things that could be paginated.

**Comment by jnoller** [comment]
Listings are the killer ones I can think of; things like start/stop/delete eh, not so much.

**Comment by kenperkins** [comment]
Pretty much all of the list resource interfaces provide an option for `limit` and `offset`. We should support the same.

**Comment by kenperkins** [comment]
My proposal for the following, which is actually based on @jrperritt's discussion in Slack:

1. Use API page sizes by default
2. Use `limit` and `marker` for all paginated APIs
3. Use `--all`, `--paginate`, `--all-pages` or some other flag to denote auto-paging

I don't believe we can auto-paginate by default because cloud files containers often have hundreds of thousands or millions of objects.

**Comment by jrperritt** [comment]
Implemented here with an `all-pages` flag: https://github.com/jrperritt/rack/commit/0353a4b9ecc353a7f69d8db5fa696d894bb0b425
