### ISSUE TITLE
Streamline installation for OSX and Linux

### ISSUE THREAD

**Issue by everett-toews** [jrperritt/rack#57]
I think we should be able to reduce installation on OSX and Linux to 2 commands.

```
$ curl -L https://rack.developer.rackspace.com/rack-`uname -s`-`uname -m` > /usr/local/bin/rack
$ chmod +x /usr/local/bin/rack
```

This assumes a few things:
* We have a proper domain name to replace the Cloud Files CDN domain name
* The binaries are saved with capitalized Darwin and Linux to account of the output of `uname -s`
* We provide 32 and 64 bit binaries. If not, we can just drop the `uname -m`

I also see we `mkdir -p /usr/local/bin/` and `export PATH=$PATH:/usr/local/bin`. What OSX and Linux distros don't come with `/usr/local/bin/` already?

I picked this stuff up from the [installation instructions for docker-compose](https://docs.docker.com/compose/install/#install-compose).

**Comment by rgbkrk** [comment]
I like that.

Our "choice" of lowercase versions of Darwin and Linux actually come from go/gimme. We should make it easier for the user though, so that could be [accommodated in the build script](https://github.com/jrperritt/rack/blob/cbec19fd0d1ab16a0e64945d8022cb3409c09dd2/script/prep-travis-release.sh).

[`/usr/local` doesn't exist on a plain vanilla install of OS X](http://apple.stackexchange.com/questions/157979/usr-local-doesnt-exist-in-fresh-install-yosemite).

**Comment by rgbkrk** [comment]
I'm really having trouble finding good citations other than some old articles about 32-bit vs. 64-bit, but I'd like to make a leap to say that 64-bit is likely on a developer box.

http://stackoverflow.com/questions/18281235/prevalence-of-64bit-vs-32bit-platforms

**Comment by jnoller** [comment]
/usr/local does not exist on plain OSX installs (it's an xcode / homebrew artifact) 

I would prefer NOT to assume the "run a magic curl command" model that docker and others use; our goal isn't for power users, its for support people and others who may hit an error because:

curl -L https://rack.developer.rackspace.com/rack-`uname -s`-`uname -m` > /usr/local/bin/rack

fails because they don't have access to the uname binary, or they don't have /usr/local - I'd rather assume they are not native OSX / developer users - or even native cloud users.

**Comment by rgbkrk** [comment]
Nor do they necessarily have `curl`.

**Comment by jnoller** [comment]
Correct

**Comment by everett-toews** [comment]
Alright. Power users will be able to figure this stuff out themselves anyway. And #58 will make it even easier.
