### ISSUE TITLE
Options for consistent approach to piping across services

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#60]
@jrperritt and I have spent some time ideating on possible strategies for piping. We've got a proposal that we want to try out with everyone.

All commands that allow piped inputs require an explicit `--stdin` flag.
All commands that allow piped inputs require the caller to explicitly declare what flag is coming in on stdin.

These are all examples where we'd use `stdin` and a combination of required flags.

`cat ids.txt | rack servers instance delete --id --stdin`
`cat names.txt | rack servers instance delete --name --stdin`
`cat foo.txt | rack files object create --container mycontainer name foo.txt --contents --stdin`
`cat ~/.ssh/id_rsa.pub | rack servers keys create --name my-key --public-key --stdin`

This approach maintains consistency on functions like upload on keys or object when not using `--stdin`:

`rack files object create --container mycontainer name foo.txt --contents "{\"data\":\"asdf1234\"}"`
`rack servers keys create --name my-key --public-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOltMjiD35ZteXKGIqkSVDLwnj8n5ZCuoB9Lb7yf23/nCfdUsp1Yw1sjsaWege7969bRWMSx0nB7r9b3rbJAISKfaA4wSSswKI4eaU1fKAN6JSf3kvCI8y12cqC2bsFY0FIakiVrO4gewBzo/JH5f0QqwKIsj2QDg2m8d/jZkHxAcY0jrIa1PHbP51B35KrgV1+ga6kzVmYMqzR/jhURJzRhlb3yn0oLhBOLpC2dsnS2cnTTqsdgaHFV8927bWJA0sYnkv2vJqetqAu/9E4WJZQD36IjWoNKT+4uOIU58PefOhhttUu5NPa0vVruADSlVH+N5ULoIZb0oYqvZjX3Wj ken.perkins@rackspace.com`

To provide the capability to use local files as inputs, but not being piped, we'll use explicit flags to differentiate inline content from local files:

`rack files object create --container mycontainer --name foo.txt --file ./foo.txt`
`rack servers keys create --name my-key --file ~/.ssh/id_rsa.pub`

What do ya'll think?

**Comment by rgbkrk** [comment]
Ooh my favorite topic!

**Comment by rgbkrk** [comment]
Definitely agree with the `--file` ./foo.txt. Note: There's an implicit action there about `create` meaning that you're reading from the file rather than writing output to it. Same thing if you download. I would hope this works if you pass it `/dev/stdin` or `/dev/stdout` as well.

Generally, I'll say I'm in favor of the `--stdin` flag. The explicit flag makes sense as well. It's just too bad we can't agree on using GUIDs otherwise.

As is with this design:

```
$ rack servers instance list --fields=id | tail -n +2 |  rack servers instance reboot --id --stdin
```

Which really isn't too bad. The only thing I'd want to add for people to compose on our own tool is likely a `-q` option to remove the header.

```
$ rack servers instance list --fields=id -q | rack servers instance reboot --id --stdin
```

If the id was implied with a `-q`, it would read like

```
$ rack servers instance list -q | rack servers instance reboot --stdin
```

**Comment by kenperkins** [comment]
@rgbkrk can you clarify what you mean about the implicit `create` meaning? I'm not sure I follow.

While I know docker uses `-q` to remove the header, I'm not certain that's the best flag as I find it confusing what `-q` means.

**Comment by rgbkrk** [comment]
wget uses `-q` for quiet as well:

```
       -q
       --quiet
           Turn off Wget's output.
```

but it means a total silencing. I will concede and say that I don't think `-q` makes sense here.

**Comment by kenperkins** [comment]
Back to the discussion at hand, I *think* @rgbkrk is endorsing the approach enumerated above.

**Comment by rgbkrk** [comment]
Yeah, we're not limiting ourselves by using this explicit approach right now. :+1:

**Comment by jrperritt** [comment]
Update: Due to the way the `cli` library (and, in turn, the Go standard library) parses command-line flags, a flag cannot accept both 0 values and 1 value. What this means is the following:
For this command: `cat ids.txt | rack servers instance get --id --stdin`
- if `id` is defined as a boolean flag, `stdin` will be interpreted correctly as a boolean flag (though of course the value of `id` can only be `true` or `false`), and 
- if `id` is defined as a string flag, `stdin` will be interpreted as its value (equivalent to `--id="--stdin"`).

Having said that, I think we have 2 reasonable options to continue down this path (more may follow after sleep):

1. We call a function before any flag parsing is done to see if `stdin` is a given flag, and then change the appropriate flag value before the subcommand is called. Though, since each subcommand may handle piping a bit differently, we might need something like a hashmap that maps subcommands to the pipe-handling logic (probably with a type like `map[string]*func(c *cli.Context) error`). Downsides of this option would be writing our own flag parser (or copy, paste, and modify the flag parsing function in the Go standard library).

2. We have all the flags to which input can be piped as string flags and require that `stdin` come immediately after the appropriate flag (basically serving as its value). Then within the logic of each subcommand, we can check if a flag has a value of "--stdin". Of course, there'd be nothing special about the name "--stdin" in this case. It could be anything as long as it's consistent. Downsides of this option would be possible name collision (i.e. a user has an instance named "stdin") and the mandatory positioning (immediately after `--name`).

Thoughts?

**Comment by rgbkrk** [comment]
Glad you brought this up.

It's fair to say that `rack servers instance get --id --stdin` is unreasonably inconsistent anyway since normally we accept `--id=<some id>`. That would also break our doc flow, especially man pages (*This usually takes a string but sometimes it doesn't!*)

(2) would be such an awkward workflow for just about anyone.

If we want to go down options hell, we could have `--ids` and `--names` to accept batches of identifiers. That or come back to talking about globally unique IDs among services and assuming an implicit ID in the same way(s) that `nova` and `supernova` do.

**Comment by jnoller** [comment]
Is the stdin use case needed for continued services buildout for June 30?

**Comment by kenperkins** [comment]
what about making stdin take a value? `--stdin=<field>` ?

`cat ids.txt | rack servers instance delete --stdin id`
`cat foo.txt | rack files object create --container mycontainer --name /foo.txt --stdin content`

**Comment by kenperkins** [comment]
TBD if `stdin` or piping cases are required for June 30. I'd love them to be but if we can't figure out something that works, we probably won't bother.

**Comment by jrperritt** [comment]
> what about making stdin take a value? --stdin=<field> ?
That's what I'm thinking now also.

**Comment by rgbkrk** [comment]
> what about making stdin take a value?

I'm +0.5 on that. It's at least specific, though I find setting stdin to a value to be counterintuitive. Not really thinking of any other options though.

**Comment by jrperritt** [comment]
Closing; this has been implemented. Comment and/or re-open to continue discussion.
