### ISSUE TITLE
Pretty errors for expected error cases

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#88]
We should output more user-friendly errors for expected error cases. This seems to be the cause of the complaints in #84.

Known error cases we should support with pretty errors:

- [ ] No Username, API Key
- [ ] Region not found
- [ ] Region not specified (maybe same as above?)
- [ ] Profile not found
- [ ] Resource not found by id

We can append this list over time.

**Comment by jrperritt** [comment]
Yes, this is high on the priority list. There's an issue for this in Gophercloud (https://github.com/rackspace/gophercloud/issues/401), which is where this should be handled. Namely, error types should be created in and returned from Gophercloud so that third-party services (like this repo) may type assert them.

**Comment by kenperkins** [comment]
Is there a _good enough_ fix we could do in the interim if we can't do it right?

**Comment by jrperritt** [comment]
Well, we could grep the returned error for particular words or phrases like I'm doing now.

**Comment by kenperkins** [comment]
Hmm, in retrospect I think you're right, we should do it the right way. I think we can ship internal with errors as they are, but not publicly.

We should document them for internal however.

**Comment by jrperritt** [comment]
I agree. I don't *think* creating the error types in Gophercloud will be cumbersome. Famous last words... I'll try to get to it later this week.
